"""initial schema

Revision ID: eed92dfef6e0
Revises:
Create Date: 2026-08-10 14:15:25.566255

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eed92dfef6e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_schedule_items',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('applies_to_entity_type', sa.String(length=64), nullable=True),
    sa.Column('applies_to_stage_code', sa.String(length=64), nullable=True),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('fee_type', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('notification_templates',
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('title_template', sa.String(length=255), nullable=False),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category')
    )
    op.create_table('partners',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('accent_color', sa.String(length=9), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('rate_limit_per_hour', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partners_slug'), ['slug'], unique=True)

    op.create_table('payment_events',
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('dedup_key', sa.String(length=128), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'dedup_key', name='uq_payment_event_dedup')
    )
    op.create_table('public_holidays',
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('holiday_date')
    )
    op.create_table('report_snapshots',
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_date')
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('signature_templates',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('merge_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('secondary_phone', sa.String(length=20), nullable=True),
    sa.Column('is_whatsapp_reachable', sa.Boolean(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('is_phone_verified', sa.Boolean(), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('supervisor_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=True)

    op.create_table('workflow_definitions',
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('variant', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_definitions_entity_type'), ['entity_type'], unique=False)

    op.create_table('audit_logs',
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)

    op.create_table('business_cases',
    sa.Column('case_number', sa.String(length=32), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('assigned_officer_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('workflow_definition_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('onboarding_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_stage_id', sa.UUID(), nullable=True),
    sa.Column('partner_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_officer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['current_stage_id'], ['case_stages.id'], use_alter=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.ForeignKeyConstraint(['workflow_definition_id'], ['workflow_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('business_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_cases_case_number'), ['case_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_business_cases_partner_id'), ['partner_id'], unique=False)

    op.create_table('notification_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('in_app_enabled', sa.Boolean(), nullable=False),
    sa.Column('sms_enabled', sa.Boolean(), nullable=True),
    sa.Column('whatsapp_enabled', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category', name='uq_notification_pref_user_category')
    )
    op.create_table('onboarding_drafts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('otp_codes',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('otp_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_otp_codes_identifier'), ['identifier'], unique=False)

    op.create_table('partner_api_keys',
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partner_api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partner_api_keys_prefix'), ['prefix'], unique=True)

    op.create_table('partner_webhooks',
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('secret', sa.String(length=128), nullable=False),
    sa.Column('event_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referral_codes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('referral_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_referral_codes_code'), ['code'], unique=True)

    op.create_table('referrals',
    sa.Column('referrer_id', sa.UUID(), nullable=False),
    sa.Column('referred_user_id', sa.UUID(), nullable=False),
    sa.Column('rewarded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['referred_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referred_user_id')
    )
    op.create_table('stage_definitions',
    sa.Column('workflow_definition_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('is_gated_by_payment', sa.Boolean(), nullable=False),
    sa.Column('deadline_days', sa.Integer(), nullable=True),
    sa.Column('sla_hours', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_definition_id'], ['workflow_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_reference', sa.String(length=128), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_provider_reference'), ['provider_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_user_id'), ['user_id'], unique=False)

    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('business_profiles',
    sa.Column('business_case_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('logo_s3_key', sa.String(length=512), nullable=True),
    sa.Column('default_currency', sa.String(length=8), nullable=False),
    sa.Column('is_vat_registered', sa.Boolean(), nullable=False),
    sa.Column('vat_rate_bps', sa.Integer(), nullable=False),
    sa.Column('vat_number', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_case_id'], ['business_cases.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_case_id')
    )
    op.create_table('case_stages',
    sa.Column('business_case_id', sa.UUID(), nullable=False),
    sa.Column('stage_definition_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_gated_by_payment', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['business_case_id'], ['business_cases.id'], ),
    sa.ForeignKeyConstraint(['stage_definition_id'], ['stage_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_invoices',
    sa.Column('business_case_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=32), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('vat_rate_bps', sa.Integer(), nullable=False),
    sa.Column('subtotal_minor', sa.Integer(), nullable=False),
    sa.Column('vat_minor', sa.Integer(), nullable=False),
    sa.Column('total_minor', sa.Integer(), nullable=False),
    sa.Column('share_token', sa.String(length=64), nullable=True),
    sa.Column('pdf_s3_key', sa.String(length=512), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_case_id'], ['business_cases.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_invoices_business_case_id'), ['business_case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_invoices_share_token'), ['share_token'], unique=True)

    op.create_table('cofounder_invites',
    sa.Column('business_case_id', sa.UUID(), nullable=False),
    sa.Column('inviter_id', sa.UUID(), nullable=False),
    sa.Column('invitee_name', sa.String(length=255), nullable=False),
    sa.Column('invitee_email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=48), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('accepted_user_id', sa.UUID(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['accepted_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['business_case_id'], ['business_cases.id'], ),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_case_id', 'invitee_email', name='uq_cofounder_case_email')
    )
    with op.batch_alter_table('cofounder_invites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cofounder_invites_business_case_id'), ['business_case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cofounder_invites_token'), ['token'], unique=True)

    op.create_table('compliance_obligations',
    sa.Column('business_case_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('recurrence', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reminded_marks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_case_id'], ['business_cases.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compliance_obligations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_obligations_business_case_id'), ['business_case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_obligations_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_obligations_due_date'), ['due_date'], unique=False)

    op.create_table('expenses',
    sa.Column('business_case_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('receipt_s3_key', sa.String(length=512), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_case_id'], ['business_cases.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_business_case_id'), ['business_case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_expense_date'), ['expense_date'], unique=False)

    op.create_table('mail_items',
    sa.Column('business_case_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('logged_by_user_id', sa.UUID(), nullable=False),
    sa.Column('sender', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('urgency', sa.String(length=16), nullable=False),
    sa.Column('scan_s3_key', sa.String(length=512), nullable=True),
    sa.Column('scan_uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shred_after', sa.Date(), nullable=True),
    sa.Column('shredded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_case_id'], ['business_cases.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['logged_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mail_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mail_items_business_case_id'), ['business_case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mail_items_client_id'), ['client_id'], unique=False)

    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('related_case_id', sa.UUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['related_case_id'], ['business_cases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('partner_webhook_deliveries',
    sa.Column('webhook_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['webhook_id'], ['partner_webhooks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quotes',
    sa.Column('business_case_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('subtotal_government_minor', sa.Integer(), nullable=False),
    sa.Column('subtotal_service_minor', sa.Integer(), nullable=False),
    sa.Column('total_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['business_case_id'], ['business_cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_case_id')
    )
    op.create_table('registered_address_enrollments',
    sa.Column('business_case_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('office_address', sa.String(length=512), nullable=False),
    sa.Column('consent_text', sa.Text(), nullable=False),
    sa.Column('consent_ip', sa.String(length=64), nullable=True),
    sa.Column('consented_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_case_id'], ['business_cases.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_case_id')
    )
    with op.batch_alter_table('registered_address_enrollments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registered_address_enrollments_client_id'), ['client_id'], unique=False)

    op.create_table('task_definitions',
    sa.Column('stage_definition_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('assignee_type', sa.String(length=16), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('requires_document', sa.Boolean(), nullable=False),
    sa.Column('required_document_type', sa.String(length=64), nullable=True),
    sa.Column('allowed_transition_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['stage_definition_id'], ['stage_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_tasks',
    sa.Column('case_stage_id', sa.UUID(), nullable=False),
    sa.Column('task_definition_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('assignee_type', sa.String(length=16), nullable=False),
    sa.Column('assigned_user_id', sa.UUID(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('requires_document', sa.Boolean(), nullable=False),
    sa.Column('required_document_type', sa.String(length=64), nullable=True),
    sa.Column('allowed_transition_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('linked_document_id', sa.UUID(), nullable=True),
    sa.Column('government_reference_note', sa.Text(), nullable=True),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sla_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sla_breached_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_stage_id'], ['case_stages.id'], ),
    sa.ForeignKeyConstraint(['linked_document_id'], ['documents.id'], use_alter=True),
    sa.ForeignKeyConstraint(['task_definition_id'], ['task_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_invoice_line_items',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('quantity_milli', sa.Integer(), nullable=False),
    sa.Column('unit_price_minor', sa.Integer(), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['client_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('business_case_id', sa.UUID(), nullable=False),
    sa.Column('quote_id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('subtotal_government_minor', sa.Integer(), nullable=False),
    sa.Column('subtotal_service_minor', sa.Integer(), nullable=False),
    sa.Column('total_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('receipt_s3_key', sa.String(length=512), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_case_id'], ['business_cases.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_table('mail_forward_requests',
    sa.Column('mail_item_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('forwarding_address', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('handled_by_user_id', sa.UUID(), nullable=True),
    sa.Column('is_forwarded_flag', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['handled_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mail_item_id'], ['mail_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_deliveries',
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cost_minor', sa.Integer(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quote_line_items',
    sa.Column('quote_id', sa.UUID(), nullable=False),
    sa.Column('fee_schedule_item_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('fee_type', sa.String(length=16), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['fee_schedule_item_id'], ['fee_schedule_items.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_requests',
    sa.Column('obligation_id', sa.UUID(), nullable=False),
    sa.Column('business_case_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('assigned_officer_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_officer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['business_case_id'], ['business_cases.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['obligation_id'], ['compliance_obligations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('business_case_id', sa.UUID(), nullable=False),
    sa.Column('case_task_id', sa.UUID(), nullable=True),
    sa.Column('document_type_code', sa.String(length=64), nullable=False),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=False),
    sa.Column('is_vault', sa.Boolean(), nullable=False),
    sa.Column('current_version_number', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_case_id'], ['business_cases.id'], ),
    sa.ForeignKeyConstraint(['case_task_id'], ['case_tasks.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_line_items',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('fee_type', sa.String(length=16), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_reference', sa.String(length=128), nullable=True),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_manual_credit', sa.Boolean(), nullable=False),
    sa.Column('recorded_by_user_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referral_credits',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('applied_invoice_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['applied_invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('referral_credits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_referral_credits_user_id'), ['user_id'], unique=False)

    op.create_table('case_messages',
    sa.Column('business_case_id', sa.UUID(), nullable=False),
    sa.Column('sender_user_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('attachment_document_id', sa.UUID(), nullable=True),
    sa.Column('client_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('officer_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['attachment_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['business_case_id'], ['business_cases.id'], ),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_messages_business_case_id'), ['business_case_id'], unique=False)

    op.create_table('document_versions',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('s3_key', sa.String(length=512), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('upload_status', sa.String(length=16), nullable=False),
    sa.Column('review_status', sa.String(length=16), nullable=False),
    sa.Column('review_reason_code', sa.String(length=32), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('virus_scan_status', sa.String(length=16), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signature_requests',
    sa.Column('business_case_id', sa.UUID(), nullable=False),
    sa.Column('case_task_id', sa.UUID(), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_reference', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('merged_html', sa.Text(), nullable=False),
    sa.Column('signed_document_id', sa.UUID(), nullable=True),
    sa.Column('signed_pdf_s3_key', sa.String(length=512), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_case_id'], ['business_cases.id'], ),
    sa.ForeignKeyConstraint(['case_task_id'], ['case_tasks.id'], ),
    sa.ForeignKeyConstraint(['signed_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['signature_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signature_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signature_requests_business_case_id'), ['business_case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signature_requests_provider_reference'), ['provider_reference'], unique=False)

    op.create_table('signature_parties',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('sign_token', sa.String(length=64), nullable=False),
    sa.Column('signature_type', sa.String(length=16), nullable=True),
    sa.Column('signature_data', sa.Text(), nullable=True),
    sa.Column('signed_ip', sa.String(length=64), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['signature_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signature_parties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signature_parties_sign_token'), ['sign_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signature_parties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signature_parties_sign_token'))

    op.drop_table('signature_parties')
    with op.batch_alter_table('signature_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signature_requests_provider_reference'))
        batch_op.drop_index(batch_op.f('ix_signature_requests_business_case_id'))

    op.drop_table('signature_requests')
    op.drop_table('document_versions')
    with op.batch_alter_table('case_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_messages_business_case_id'))

    op.drop_table('case_messages')
    with op.batch_alter_table('referral_credits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referral_credits_user_id'))

    op.drop_table('referral_credits')
    op.drop_table('payments')
    op.drop_table('invoice_line_items')
    op.drop_table('documents')
    op.drop_table('service_requests')
    op.drop_table('quote_line_items')
    op.drop_table('notification_deliveries')
    op.drop_table('mail_forward_requests')
    op.drop_table('invoices')
    op.drop_table('client_invoice_line_items')
    op.drop_table('case_tasks')
    op.drop_table('task_definitions')
    with op.batch_alter_table('registered_address_enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registered_address_enrollments_client_id'))

    op.drop_table('registered_address_enrollments')
    op.drop_table('quotes')
    op.drop_table('partner_webhook_deliveries')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('mail_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mail_items_client_id'))
        batch_op.drop_index(batch_op.f('ix_mail_items_business_case_id'))

    op.drop_table('mail_items')
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_expense_date'))
        batch_op.drop_index(batch_op.f('ix_expenses_business_case_id'))

    op.drop_table('expenses')
    with op.batch_alter_table('compliance_obligations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_obligations_due_date'))
        batch_op.drop_index(batch_op.f('ix_compliance_obligations_client_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_obligations_business_case_id'))

    op.drop_table('compliance_obligations')
    with op.batch_alter_table('cofounder_invites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cofounder_invites_token'))
        batch_op.drop_index(batch_op.f('ix_cofounder_invites_business_case_id'))

    op.drop_table('cofounder_invites')
    with op.batch_alter_table('client_invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_invoices_share_token'))
        batch_op.drop_index(batch_op.f('ix_client_invoices_business_case_id'))

    op.drop_table('client_invoices')
    op.drop_table('case_stages')
    op.drop_table('business_profiles')
    op.drop_table('user_roles')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_provider_reference'))

    op.drop_table('subscriptions')
    op.drop_table('stage_definitions')
    op.drop_table('referrals')
    with op.batch_alter_table('referral_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referral_codes_code'))

    op.drop_table('referral_codes')
    op.drop_table('partner_webhooks')
    with op.batch_alter_table('partner_api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partner_api_keys_prefix'))

    op.drop_table('partner_api_keys')
    with op.batch_alter_table('otp_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_otp_codes_identifier'))

    op.drop_table('otp_codes')
    op.drop_table('onboarding_drafts')
    op.drop_table('notification_preferences')
    with op.batch_alter_table('business_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_cases_partner_id'))
        batch_op.drop_index(batch_op.f('ix_business_cases_case_number'))

    op.drop_table('business_cases')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('workflow_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_definitions_entity_type'))

    op.drop_table('workflow_definitions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('signature_templates')
    op.drop_table('roles')
    op.drop_table('report_snapshots')
    op.drop_table('public_holidays')
    op.drop_table('payment_events')
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partners_slug'))

    op.drop_table('partners')
    op.drop_table('notification_templates')
    op.drop_table('fee_schedule_items')
    # ### end Alembic commands ###
